overrides:
  "@vitejs/plugin-vue": "^6.0.7"

allowBuilds:
  "@infisical/cli": true
  "@parcel/watcher": true
  "@sentry/cli": true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - astro
  - "@astrojs/*"
