overrides:
  "@vitejs/plugin-vue": "^6.0.7"

allowBuilds:
  "@infisical/cli": true
  "@parcel/watcher": true
  "@sentry/cli": true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - "@felix_berlin/*"
  - astro-breadcrumbs
  - astro-matomo
  - "@astrojs/markdown-satteri@0.3.1"
  - "@astrojs/vue@7.0.0 || 7.0.1"
  - astro@7.0.0 || 7.0.3
  - "@sentry/browser-utils@10.62.0"
  - "@sentry/browser@10.62.0"
  - "@sentry/core@10.62.0"
  - "@sentry/feedback@10.62.0"
  - "@sentry/replay-canvas@10.62.0"
  - "@sentry/replay@10.62.0"
  - js-yaml
  - stylelint@17.14.0
  - "@iconify-json/lucide@1.2.115"
  - virtua@0.49.2
  - autoprefixer@10.5.3
  - compromise@14.16.0
  - de-compromise@0.1.0
  - miniflare@4.20260710.0 || 4.20260721.0
  - wrangler@4.111.0 || 4.113.0
  - '@cloudflare/workerd-darwin-64@1.20260721.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260721.1'
  - '@cloudflare/workerd-linux-64@1.20260721.1'
  - '@cloudflare/workerd-linux-arm64@1.20260721.1'
  - '@cloudflare/workerd-windows-64@1.20260721.1'
  - '@infisical/cli@0.43.111'
  - '@semantic-release/changelog@7.0.0'
  - '@semantic-release/git@11.0.0'
  - nanostores@1.4.1
  - workerd@1.20260721.1
