overrides:
  "@vitejs/plugin-vue": "^6.0.7"

allowBuilds:
  "@infisical/cli": true
  "@parcel/watcher": true
  "@sentry/cli": true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.1'
  - '@astrojs/vue@7.0.0'
  - astro@7.0.0
  - '@sentry/browser-utils@10.62.0'
  - '@sentry/browser@10.62.0'
  - '@sentry/core@10.62.0'
  - '@sentry/feedback@10.62.0'
  - '@sentry/replay-canvas@10.62.0'
  - '@sentry/replay@10.62.0'
  - astro@7.0.3
  - stylelint@17.14.0
