name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ✅
      uses: actions/checkout@v7

    - name: Fetch secrets from Infisical 🔐
      uses: Infisical/secrets-action@v1.0.16
      with:
        method: "oidc"
        identity-id: "5f0ad8b7-0224-48ca-b233-abbd59f2eb68"
        project-slug: "berliner-schnauze"
        env-slug: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}
        domain: "https://infisical.kasimir.dev"

    - name: Setup pnpm 🛠️
      uses: pnpm/action-setup@v6

    - name: Setup Node.js 🔧
      uses: actions/setup-node@v7
      with:
        node-version: lts/*
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 14
