name: Release
on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write  # required for GitHub OIDC with Infisical

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Fetch secrets from Infisical 🔐
        uses: infisical/secrets-action@v1
        with:
          method: oidc
          project-slug: berliner-schnauze
          env-slug: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ env.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        with:
          environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
