name: Release
on:
  push:
    branches:
      - main
      - beta

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch secrets from Infisical (root) 🔐
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "5f0ad8b7-0224-48ca-b233-abbd59f2eb68"
          project-slug: "berliner-schnauze"
          env-slug: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}
          domain: "https://infisical.kasimir.dev"

      - name: Fetch secrets from Infisical (/GitHub) 🔐
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "5f0ad8b7-0224-48ca-b233-abbd59f2eb68"
          project-slug: "berliner-schnauze"
          env-slug: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}
          domain: "https://infisical.kasimir.dev"
          secret-path: "/GitHub"

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ env.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ env.GIT_COMMITTER_EMAIL }}
        run: npx semantic-release

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ env.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        with:
          environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
