name: Unit tests
on:
  pull_request:
  push:
    branches:
      - main
      - beta

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v7

      - name: Fetch secrets from Infisical 🔐
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "5f0ad8b7-0224-48ca-b233-abbd59f2eb68"
          project-slug: "berliner-schnauze"
          env-slug: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}
          domain: "https://infisical.kasimir.dev"

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies 🛠️
        run: pnpm i

      - name: Run Vitest (with coverage report) 🧪
        run: pnpm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          directory: ./tests/unit/coverage
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          report_type: test_results
          files: ./tests/unit/junit-report.xml
          token: ${{ env.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}
